In [1]:
import pandas as pd

In [2]:
csv_file = "Resources\Site_2_Projections\Site_2_W16_projections.csv"
four44_df = pd.read_csv(csv_file)

four44_df.head()

,Season,Week,PID,Player,Pos,Team,Opp,aFPA,aFPA Rk,FFPts,...,Rec,Rec Yds,Rec TD,Pa1D,Ru1D,Rec1D,Fum,XP,FG,Grade
0,2018,16,mahomp1,Patrick Mahomes,QB,KC,@SEA,18.0,21,21.7,...,0.0,0.0,0.0,14.6,1.1,0.0,0.2,0.0,0.0,A-Game
1,2018,16,breesd1,Drew Brees,QB,NO,PIT,14.6,6,20.2,...,0.0,0.0,0.0,14.3,0.1,0.0,0.2,0.0,0.0,A-Game
2,2018,16,wilsor1,Russell Wilson,QB,SEA,KC,20.3,31,20.1,...,0.0,0.0,0.0,12.8,1.8,0.0,0.2,0.0,0.0,A-Game
3,2018,16,lucka1,Andrew Luck,QB,IND,NYG,15.2,10,18.8,...,0.0,0.0,0.0,13.6,0.7,0.0,0.2,0.0,0.0,A-Game
4,2018,16,roethb1,Ben Roethlisberger,QB,PIT,@NO,15.5,12,18.6,...,0.0,0.0,0.0,14.6,0.5,0.0,0.3,0.0,0.0,A-Game

In [3]:
# Applying Fanduel uniform scoring system to Fantasy Sharks raw predictions and creating a new column with the results
four44_df['Site 2'] = four44_df['Pass Yds'] * .04 + four44_df['Rush Yds'] * .1 + four44_df['Rec Yds'] * .1 + \
four44_df['Pass TD'] * 4 + four44_df['Rush TD'] * 6 + four44_df['Rec TD'] * 6 + four44_df['Rec'] * .5 + four44_df['INT'] * -1 \
+ four44_df['Fum'] * -2

four44_df.head()

,Season,Week,PID,Player,Pos,Team,Opp,aFPA,aFPA Rk,FFPts,...,Rec Yds,Rec TD,Pa1D,Ru1D,Rec1D,Fum,XP,FG,Grade,Site 2
0,2018,16,mahomp1,Patrick Mahomes,QB,KC,@SEA,18.0,21,21.7,...,0.0,0.0,14.6,1.1,0.0,0.2,0.0,0.0,A-Game,22.662
1,2018,16,breesd1,Drew Brees,QB,NO,PIT,14.6,6,20.2,...,0.0,0.0,14.3,0.1,0.0,0.2,0.0,0.0,A-Game,20.780
2,2018,16,wilsor1,Russell Wilson,QB,SEA,KC,20.3,31,20.1,...,0.0,0.0,12.8,1.8,0.0,0.2,0.0,0.0,A-Game,20.870
3,2018,16,lucka1,Andrew Luck,QB,IND,NYG,15.2,10,18.8,...,0.0,0.0,13.6,0.7,0.0,0.2,0.0,0.0,A-Game,19.696
4,2018,16,roethb1,Ben Roethlisberger,QB,PIT,@NO,15.5,12,18.6,...,0.0,0.0,14.6,0.5,0.0,0.3,0.0,0.0,A-Game,19.570

In [4]:
#dropping unneeded columns
four44_df = four44_df.drop([
 'PID',
 'Pos',
 'Team',
 'Opp',
 'aFPA',
 'aFPA Rk',
 'FFPts',
 'Comp',
 'Pass Att',
 'Pass Yds',
 'Pass TD',
 'INT',
 'Rush Att',
 'Rush Yds',
 'Rush TD',
 'Rec',
 'Rec Yds',
 'Rec TD',
 'Pa1D',
 'Ru1D',
 'Rec1D',
 'Fum',
 'XP',
 'FG',
 'Grade'], axis=1)

# Rename player column to "Name"
four44_df.rename(columns = {"Player": "Name"}, inplace = True)

four44_df.head()

   Season  Week                Name  Site 2
0    2018    16     Patrick Mahomes  22.662
1    2018    16          Drew Brees  20.780
2    2018    16      Russell Wilson  20.870
3    2018    16         Andrew Luck  19.696
4    2018    16  Ben Roethlisberger  19.570

In [8]:
csv_file = "Resources\Fantasy_Sharks_Projections\fantasysharks_W16_Projections.csv"
sharks_df = pd.read_csv(csv_file)
sharks_df.head()

FileNotFoundError: File b'Resources\\Fantasy_Sharks_Projections\x0cantasysharks_W16_Projections.csv' does not exist

In [ ]:
# Splitting the name into 2 seperate columns
sharks_df[['Last Name','First Name']] = sharks_df['Name'].str.split(', ',expand=True)
sharks_df.head()

In [ ]:
# Recombine names into one column in the order of First Last
sharks_df['Name'] = sharks_df['First Name'].str.cat(sharks_df['Last Name'],sep=" ")
sharks_df.head()

In [ ]:
# Applying Fanduel uniform scoring system to Fantasy Sharks raw predictions and creating a new column with the results
sharks_df['Fantasy Sharks'] = sharks_df['Yards'] * .04 + sharks_df['Yards.1'] * .1 + sharks_df['Yards.2'] * .1 + \
sharks_df['TD'] * 4 + sharks_df['TD.1'] * 6 + sharks_df['TD.2'] * 6 + sharks_df['Rec'] * .5 + sharks_df['Int'] * -1 

sharks_df.head()

In [ ]:
sharks_df = sharks_df.drop(['ID', 'Rank', 'First Name', 'Last Name', 'Comp', 'Yards', 'TD', 'TD.1', 
'TD.2', 'Int', 'Att', 'Yards.1', 'Yards.2', 'Rec', 'Fantasy Points'], axis=1)
sharks_df.head()

In [ ]:
combined_df = sharks_df.merge(four44_df, on=['Name'], sort=False)

combined_df.round({'Fantasy Sharks': 1, 'Site 2': 1})


pd.options.display.float_format = '{:,.2f}'.format

combined_df = combined_df[['Season', 'Week', 'Name', 'Pos', 'Team', 'Opp', 'Fantasy Sharks', 'Site 2']]

combined_df.head()

In [ ]:
url = "http://fantasy.nfl.com/research/projections#researchProjections=researchProjections%2C%2Fresearch%2Fprojections%253Foffset%253D{i}%2526position%253DO%2526sort%253DprojectedPts%2526statCategory%253DprojectedStats%2526statSeason%253D2018%2526statType%253DweekProjectedStats%2526statWeek%253D16%2Creplace"
nfl = pd.read_html(url)
# nfl_df = pd.DataFrame(nfl)
# nfl_df
# nfl

# nfl_df = pd.DataFrame(nfl.row.str.split(' ',1).tolist())
nfl_df['Name'] = df['First Name'].str.cat(df['Last Name'],sep=" ")
nfl_df

In [ ]:
#researchProjections=researchProjections%2C%2Fresearch%2Fprojections%253Foffset%253D1%2526position%253DO%2526sort%253DprojectedPts%2526statCategory%253DprojectedStats%2526statSeason%253D2018%2526statType%253DweekProjectedStats%2526statWeek%253D16%2Creplace
#researchProjections=researchProjections%2C%2Fresearch%2Fprojections%253Foffset%253D26%2526position%253DO%2526sort%253DprojectedPts%2526statCategory%253DprojectedStats%2526statSeason%253D2018%2526statType%253DweekProjectedStats%2526statWeek%253D16%2Creplace    
#researchProjections=researchProjections%2C%2Fresearch%2Fprojections%253Foffset%253D51%2526position%253DO%2526sort%253DprojectedPts%2526statCategory%253DprojectedStats%2526statSeason%253D2018%2526statType%253DweekProjectedStats%2526statWeek%253D16%2Creplace